config/routes.rb
Rails.application.routes.draw do  
  root to: 'home#show'

  # Don't allow users to create/delete/update the record for now
  resources :users, only: [:index, :show] do
    resources :drink_histories, only: [:index, :show]
    resources :reviews, only: [:index, :show]
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :beers, only: [:show, :index] do
    resources :drink_histories, only: [:show, :index]
    resources :reviews, only: [:show, :index]
  end

  resources :drink_histories, only: [:show, :index]
  resources :reviews, only: [:show, :index]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/drink_history.rb
class DrinkHistory < ApplicationRecord
  belongs_to :user
  belongs_to :beer
end

app/controllers/drink_histories_controller.rb
class DrinkHistoriesController < ApplicationController
  before_action :set_drink_history, only: [:show, :edit, :update, :destroy]

  # GET /drink_histories
  # GET /drink_histories.json
  def index
    @drink_histories = DrinkHistory.first(100)
  end

  # GET /drink_histories/1
  # GET /drink_histories/1.json
  def show
  end

  # GET /drink_histories/new
  # def new
  #   @drink_history = DrinkHistory.new
  # end

  # # GET /drink_histories/1/edit
  # def edit
  # end

  # # POST /drink_histories
  # # POST /drink_histories.json
  # def create
  #   @drink_history = DrinkHistory.new(drink_history_params)

  #   respond_to do |format|
  #     if @drink_history.save
  #       format.html { redirect_to @drink_history, notice: 'Drink history was successfully created.' }
  #       format.json { render :show, status: :created, location: @drink_history }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @drink_history.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /drink_histories/1
  # # PATCH/PUT /drink_histories/1.json
  # def update
  #   respond_to do |format|
  #     if @drink_history.update(drink_history_params)
  #       format.html { redirect_to @drink_history, notice: 'Drink history was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @drink_history }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @drink_history.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /drink_histories/1
  # # DELETE /drink_histories/1.json
  # def destroy
  #   @drink_history.destroy
  #   respond_to do |format|
  #     format.html { redirect_to drink_histories_url, notice: 'Drink history was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drink_history
      @drink_history = DrinkHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def drink_history_params
      params.require(:drink_history).permit(:user_id, :beer_id)
    end
end

app/views/drink_histories/_form.html.haml
= form_for @drink_history do |f|
  - if @drink_history.errors.any?
    #error_explanation
      %h2= "#{pluralize(@drink_history.errors.count, "error")} prohibited this drink_history from being saved:"
      %ul
        - @drink_history.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :beer
    = f.text_field :beer
  .actions
    = f.submit 'Save'

app/views/drink_histories/edit.html.haml
%h1 Editing drink_history

= render 'form'

= link_to 'Show', @drink_history
\|
= link_to 'Back', drink_histories_path

app/views/drink_histories/index.html.haml
%h1 Listing drink_histories

%table
  %thead
    %tr
      %th User
      %th Beer
      %th
      %th Date
      %th

  %tbody
    - @drink_histories.each do |drink_history|
      %tr
        %td= link_to drink_history.user.name, drink_history.user
        %td= link_to drink_history.beer.name, drink_history.beer
        %td= drink_history.beer.image_path_medium.present? ? (image_tag drink_history.beer.image_path_medium, size: "20x20") : (image_tag 'bartender.png', size: "20x20")
        %td= drink_history.created_at.strftime('%F')
        %td= link_to 'Show', drink_history

%br

app/views/drink_histories/new.html.haml
%h1 New drink_history

= render 'form'

= link_to 'Back', drink_histories_path

app/views/drink_histories/show.html.haml
%p#notice= notice

%p
  %b User:
  = link_to @drink_history.user.name, @drink_history.user
%p
  %b Beer:
  = link_to @drink_history.beer.name, @drink_history.beer