config/routes.rb
Rails.application.routes.draw do  
  root to: 'home#show'

  # Don't allow users to create/delete/update the record for now
  resources :users, only: [:index, :show] do
    resources :drink_histories, only: [:index, :show]
    resources :reviews, only: [:index, :show]
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :beers, only: [:show, :index] do
    resources :drink_histories, only: [:show, :index]
    resources :reviews, only: [:show, :index]
  end

  resources :drink_histories, only: [:show, :index]
  resources :reviews, only: [:show, :index]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  email      :string
#  language   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ApplicationRecord
  has_many :drink_histories
  has_many :reviews
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def last_drink_history
    drink_histories.order("created_at desc").first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :followers, :followings]

  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end


  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user ||= User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :language, :country)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :language
    = f.text_field :language
  .field
    = f.label :country
    = f.text_field :country
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/followers.html.haml
%h1 Followers

%table
  %thead
    %tr
      %th Name
      %th Email
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, user
        %td= user.email
        - if !current_user.following?(user)
          %td= link_to 'Follow', user_relationships_url(user_id: current_user.id, relationship: {follower_id: current_user.id, following_id: user.id}), method: :post

%br

#json
= render 'shared/json_formatter'

app/views/users/followings.html.haml
%h1 Followings

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, user
        %td= user.email
        %td= link_to 'Unfollow', user_relationship_url(user_id: current_user.id, id: Relationship.find_by(follower_id: current_user.id, following_id: user.id)), method: :delete, data: {confirm: 'Are you sure?' }


%br

#json
= render 'shared/json_formatter'

app/views/users/index.html.haml
#json
= render 'shared/json_formatter'

%h1 Listing users

%table
  %thead
    %tr
      %th Name
      %th Email
      %th
      %th
      %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.name
        %td= user.email
        %td= link_to 'Show', user
        -# %td= link_to 'Edit', edit_user_path(user)
        -# %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

= paginate @users

%br

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
#json
= render 'shared/json_formatter'

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email
%p
  = link_to 'Followers', followers_user_path(@user)
  \|
  = link_to 'Followings', followings_user_path(@user)

%h2
  Your History

%table
  %thead
    %tr
      %th Beer
      %th
      %th Amount
      %th Date
  %tbody
  - DrinkHistory.where(user_id: @user.id).order("created_at desc").limit(10).each do |activity|
    %tr
      %td= link_to activity.beer.name, beer_path(activity.beer.id)
      %td= activity.beer.image_path_medium.present? ? (image_tag activity.beer.image_path_medium, size: "20x20") : (image_tag 'bartender.png', size: "20x20")
      %td= activity.amount
      %td= activity.created_at.strftime('%F')

%h2
  Friends History

%table
  %thead
    %tr
      %th Name
      %th Beer
      %th
      %th Amount
      %th Date
  %tbody
  - DrinkHistory.where(user_id: @user.followings.pluck(:id)).order("created_at desc").limit(10).each do |activity|
    %tr
      %td= link_to activity.user.name, user_path(activity.user)
      %td= link_to activity.beer.name, beer_path(activity.beer.id)
      %td= activity.beer.image_path_medium.present? ? (image_tag activity.beer.image_path_medium, size: "20x20") : (image_tag 'bartender.png', size: "20x20")
      %td= activity.amount
      %td= activity.created_at.strftime('%F')