config/routes.rb
Rails.application.routes.draw do  
  root to: 'home#show'

  # Don't allow users to create/delete/update the record for now
  resources :users, only: [:index, :show] do
    resources :drink_histories, only: [:index, :show]
    resources :reviews, only: [:index, :show]
    resources :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers
    end
  end

  resources :beers, only: [:show, :index] do
    resources :drink_histories, only: [:show, :index]
    resources :reviews, only: [:show, :index]
  end

  resources :drink_histories, only: [:show, :index]
  resources :reviews, only: [:show, :index]

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.first(100)
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  # def new
  #   @review = Review.new
  # end

  # # GET /reviews/1/edit
  # def edit
  # end

  # # POST /reviews
  # # POST /reviews.json
  # def create
  #   @review = Review.new(review_params)

  #   respond_to do |format|
  #     if @review.save
  #       format.html { redirect_to @review, notice: 'Review was successfully created.' }
  #       format.json { render :show, status: :created, location: @review }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @review.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /reviews/1
  # # PATCH/PUT /reviews/1.json
  # def update
  #   respond_to do |format|
  #     if @review.update(review_params)
  #       format.html { redirect_to @review, notice: 'Review was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @review }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @review.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /reviews/1
  # # DELETE /reviews/1.json
  # def destroy
  #   @review.destroy
  #   respond_to do |format|
  #     format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rate, :comment, :user_id, :beer_id)
    end
end

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :rate
    = f.number_field :rate
  .field
    = f.label :comment
    = f.text_area :comment
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :beer
    = f.text_field :beer
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Show', @review
\|
= link_to 'Back', reviews_path

app/views/reviews/index.html.haml
%h1 Listing reviews

%table
  %thead
    %tr
      %th Rate
      %th Comment
      %th User
      %th Beer
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.rate
        %td= review.comment
        %td= link_to review.user.name, review.user
        %td= link_to review.beer.name, review.beer
        %td= review.created_at.strftime('%F')
        %td= link_to 'Show', review

%br

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', reviews_path

app/views/reviews/show.html.haml
%p#notice= notice

%p
  %b Rate:
  = @review.rate
%p
  %b Comment:
  = @review.comment
%p
  %b User:
  = link_to @review.user.name, @review.user
%p
  %b Beer:
  = link_to @review.beer.name, @review.beer